name: Backoffice Service CI
on:
  push:
    branches-ignore:
      - "main"
      - "develop"
    tags-ignore:
      - "**"
    paths:
      - ".github/workflows/**"
      - "backoffice-service/**"
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      project-path: backoffice-service
      maven-build: true
